"use client";

import "./Dashboard.css";
import { useMemo, useState } from "react";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { useDispatch, useSelector } from "react-redux";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ArrowUpRight, Bot, CheckCircle2, ChevronRight, CircleAlert, Clock3, Code2, FolderGit2, GitPullRequest, Home, LogOut, Plus, Settings, ShieldCheck, Sparkles, TrendingUp, Zap } from "lucide-react";
import type { AppDispatch, RootState } from "@/app/redux/store";
import { logout } from "@/app/redux/slices/authslice";
import { clearAuthStorage } from "@/lib/auth/tokenStorage";
import UpgradeCard from "@/components/layout/UpgradeCard";
import AppHeader from "@/components/layout/AppHeader";

const activityData = [{ name: "Mon", reviews: 18, resolved: 12 }, { name: "Tue", reviews: 24, resolved: 18 }, { name: "Wed", reviews: 19, resolved: 15 }, { name: "Thu", reviews: 31, resolved: 23 }, { name: "Fri", reviews: 28, resolved: 22 }, { name: "Sat", reviews: 35, resolved: 28 }, { name: "Sun", reviews: 42, resolved: 34 }];
const issueData = [{ name: "Critical", value: 8, color: "#f05b72" }, { name: "Warning", value: 21, color: "#f8b84e" }, { name: "Info", value: 34, color: "#7c6cff" }];
const languageData = [{ name: "TypeScript", value: 48 }, { name: "JavaScript", value: 28 }, { name: "CSS", value: 16 }, { name: "Other", value: 8 }];
const repositories = [{ name: "codesage-web-app", branch: "main", score: 92, issues: 3, status: "Healthy", color: "#4fd39b" }, { name: "api-gateway", branch: "release/v2", score: 78, issues: 12, status: "Needs attention", color: "#f8b84e" }, { name: "design-system", branch: "develop", score: 96, issues: 1, status: "Excellent", color: "#7c6cff" }];
const initials = (name?: string | null) => name?.trim().split(/\s+/).slice(0, 2).map((part) => part[0]).join("").toUpperCase() || "CS";

export default function Dashboard() {
  const router = useRouter(); const dispatch = useDispatch<AppDispatch>(); const user = useSelector((state: RootState) => state.auth.user);
  const [period, setPeriod] = useState("7 days"); const totals = useMemo(() => activityData.reduce((sum, item) => sum + item.reviews, 0), []);
  const handleLogout = () => { clearAuthStorage(); dispatch(logout()); router.replace("/login"); };
  return <main className="codesage-page">
    <aside className="sidebar workspace-sidebar">
      <div className="brand"><div className="Brand-logo"><Image src="/mainlogo.png.png" alt="CodeSage AI" width={171} height={45} priority /></div></div>
      <nav className="sidebar-nav"><SidebarItem icon={<Home size={19} />} label="Dashboard" active /><SidebarItem icon={<FolderGit2 size={19} />} label="Repositories" onClick={() => router.push("/repositories")} /><SidebarItem icon={<Bot size={19} />} label="AI Reviews" onClick={() => router.push("/ai-reviews")} /><SidebarItem icon={<GitPullRequest size={19} />} label="Pull Requests" onClick={() => router.push("/pull-requests")} /><SidebarItem icon={<CircleAlert size={19} />} label="Issues" onClick={() => router.push("/issues")} /><SidebarItem icon={<TrendingUp size={19} />} label="Analytics" onClick={() => router.push("/analytics")} /><SidebarItem icon={<Settings size={19} />} label="Settings" onClick={() => router.push("/settings")} /></nav>
      <UpgradeCard /><div className="weekly-reviews"><div className="weekly-header"><Sparkles size={14} /><span>Weekly reviews</span><strong>12 / 20</strong></div><div className="progress-track"><div className="progress-fill" /></div></div>
      <div className="user-profile"><div className="avatar">{initials(user?.name)}</div><div className="user-info"><strong>{user?.name || "CodeSage user"}</strong><span>{user?.email || "Workspace member"}</span></div><ChevronRight size={17} /></div><button type="button" className="sidebar-item" onClick={handleLogout}><LogOut size={19} /><span>Log out</span></button>
    </aside>
    <section className="main-content workspace-main"><AppHeader /><div className="workspace-content">
      <header className="workspace-welcome"><div><p className="eyebrow">WORKSPACE OVERVIEW</p><h1>Good morning, {user?.name?.split(" ")[0] || "there"}.</h1><p>Here’s what’s happening across your codebase today.</p></div><div className="workspace-actions"><select aria-label="Select reporting period" value={period} onChange={(event) => setPeriod(event.target.value)}><option>7 days</option><option>30 days</option><option>90 days</option></select><button type="button" onClick={() => router.push("/repositories")}><Plus size={17} /> Add repository</button></div></header>
      <section className="workspace-metric-grid" aria-label="Workspace metrics"><Metric icon={<FolderGit2 size={19} />} label="Connected repositories" value="12" change="+2 this month" tone="purple" /><Metric icon={<Bot size={19} />} label="AI reviews completed" value={totals.toString()} change="18.4% vs last week" tone="blue" /><Metric icon={<CircleAlert size={19} />} label="Open issues" value="63" change="12 resolved this week" tone="amber" /><Metric icon={<ShieldCheck size={19} />} label="Average health score" value="88%" change="4.2% improvement" tone="green" /></section>
      <section className="insight-grid"><article className="workspace-card review-chart-card"><div className="card-heading"><div><p className="card-kicker">CODE QUALITY</p><h2>Review activity</h2><p>AI reviews and resolved findings over time.</p></div><button type="button" className="ghost-button">View analytics <ArrowUpRight size={15} /></button></div><div className="chart-legend"><span><i className="legend-dot purple" /> Reviews</span><span><i className="legend-dot teal" /> Resolved</span></div><div className="activity-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={activityData} margin={{ top: 8, right: 4, left: -20, bottom: 0 }}><defs><linearGradient id="reviewGradient" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#8b7cff" stopOpacity={0.42} /><stop offset="100%" stopColor="#8b7cff" stopOpacity={0} /></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--chart-grid)" strokeDasharray="3 3" /><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fill: "var(--chart-tick)", fontSize: 11 }} dy={10} /><YAxis axisLine={false} tickLine={false} tick={{ fill: "var(--chart-tick)", fontSize: 11 }} /><Tooltip contentStyle={{ background: "var(--tooltip-bg)", border: "1px solid var(--border)", borderRadius: 10, color: "var(--text)" }} /><Area type="monotone" dataKey="reviews" stroke="#8b7cff" strokeWidth={3} fill="url(#reviewGradient)" /><Area type="monotone" dataKey="resolved" stroke="#43c99a" strokeWidth={2} fill="transparent" /></AreaChart></ResponsiveContainer></div></article>
      <article className="workspace-card issue-chart-card"><div className="card-heading"><div><p className="card-kicker">FINDINGS</p><h2>Issue distribution</h2></div><button type="button" className="more-dots" aria-label="More issue options">•••</button></div><div className="donut-wrap"><ResponsiveContainer width="100%" height={186}><PieChart><Pie data={issueData} dataKey="value" nameKey="name" innerRadius={55} outerRadius={76} paddingAngle={4} stroke="none">{issueData.map((entry) => <Cell key={entry.name} fill={entry.color} />)}</Pie><Tooltip contentStyle={{ background: "var(--tooltip-bg)", border: "1px solid var(--border)", borderRadius: 10 }} /></PieChart></ResponsiveContainer><div className="donut-label"><strong>63</strong><span>open issues</span></div></div><div className="issue-legend">{issueData.map((item) => <div key={item.name}><i style={{ background: item.color }} /><span>{item.name}</span><strong>{item.value}</strong></div>)}</div></article></section>
      <section className="bottom-grid"><article className="workspace-card repository-card"><div className="card-heading"><div><p className="card-kicker">REPOSITORIES</p><h2>Repository health</h2></div><button type="button" className="ghost-button" onClick={() => router.push("/repositories")}>View all <ArrowUpRight size={15} /></button></div><div className="repository-list">{repositories.map((repo) => <div className="repository-row" key={repo.name}><div className="repository-ident"><span className="repo-mark"><Code2 size={16} /></span><div><strong>{repo.name}</strong><span>{repo.branch}</span></div></div><div className="repository-score"><span><i style={{ width: `${repo.score}%`, background: repo.color }} /></span><strong>{repo.score}</strong></div><div className="repository-status" style={{ color: repo.color }}><i style={{ background: repo.color }} />{repo.status}</div><span className="issue-count">{repo.issues} issues</span></div>)}</div></article><article className="workspace-card language-card"><div className="card-heading"><div><p className="card-kicker">CODEBASE</p><h2>Language coverage</h2></div></div><div className="language-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={languageData} layout="vertical" margin={{ top: 4, right: 25, bottom: 2, left: 0 }}><XAxis type="number" hide domain={[0, 55]} /><YAxis type="category" dataKey="name" width={82} axisLine={false} tickLine={false} tick={{ fill: "var(--chart-tick)", fontSize: 11 }} /><Tooltip cursor={{ fill: "var(--chart-hover)" }} contentStyle={{ background: "var(--tooltip-bg)", border: "1px solid var(--border)", borderRadius: 10 }} /><Bar dataKey="value" fill="#8274ff" radius={[0, 5, 5, 0]} barSize={11} /></BarChart></ResponsiveContainer></div><p className="language-note">TypeScript is used across most active repositories.</p></article></section>
      <section className="workspace-card activity-feed"><div className="card-heading"><div><p className="card-kicker">RECENT ACTIVITY</p><h2>Latest workspace updates</h2></div><button type="button" className="ghost-button">View all <ArrowUpRight size={15} /></button></div><div className="activity-list"><Activity icon={<CheckCircle2 size={17} />} tone="success" title="AI review completed for api-gateway" detail="14 suggestions generated · 6 issues resolved" time="8 min ago" /><Activity icon={<GitPullRequest size={17} />} tone="purple" title="Pull request #128 is ready to review" detail="feat: add OAuth provider connections" time="32 min ago" /><Activity icon={<Zap size={17} />} tone="amber" title="New performance insight detected" detail="Bundle size increased by 18% in codesage-web-app" time="2 hours ago" /></div></section>
    </div></section></main>;
}

function SidebarItem({ icon, label, active, onClick }: { icon: React.ReactNode; label: string; active?: boolean; onClick?: () => void }) { return <button type="button" className={`sidebar-item${active ? " active" : ""}`} onClick={onClick}>{icon}<span>{label}</span></button>; }
function Metric({ icon, label, value, change, tone }: { icon: React.ReactNode; label: string; value: string; change: string; tone: string }) { return <article className={`metric-card ${tone}`}><span className="workspace-metric-icon">{icon}</span><p>{label}</p><strong>{value}</strong><span className="workspace-metric-change"><TrendingUp size={13} /> {change}</span></article>; }
function Activity({ icon, tone, title, detail, time }: { icon: React.ReactNode; tone: string; title: string; detail: string; time: string }) { return <div className="activity-item"><span className={`activity-icon ${tone}`}>{icon}</span><div><strong>{title}</strong><p>{detail}</p></div><time><Clock3 size={13} /> {time}</time></div>; }
